name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
      - name: Download npcap sdk
        run: curl --silent --show-error --fail -o ./npcap-sdk.zip "https://npcap.com/dist/npcap-sdk-1.13.zip"
      - name: Extract npcap x64 libs
        run: |
          unzip -p npcap-sdk.zip Lib/x64/Packet.lib > Packet.lib
          unzip -p npcap-sdk.zip Lib/x64/wpcap.lib > wpcap.lib
      - name: Build pcap Windows exe
        run: cargo build --verbose --no-default-features --features pcap,stream
      - name: Move pcap exe
        run: mv target/debug/reliquary-archiver.exe target/debug/reliquary-archiver-pcap-x64.exe
      - uses: actions/upload-artifact@v4
        with:
          name: reliquary-archiver-pcap-x64
          path: target/debug/reliquary-archiver-pcap-x64.exe
      - name: Build pktmon Windows exe
        run: cargo build --verbose --no-default-features --features pktmon,stream
      - name: Move pktmon exe
        run: mv target/debug/reliquary-archiver.exe target/debug/reliquary-archiver-pktmon-x64.exe
      - uses: actions/upload-artifact@v4
        with:
          name: reliquary-archiver-pktmon-x64
          path: target/debug/reliquary-archiver-pktmon-x64.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: moonrepo/setup-rust@v1
    - name: Install libpcap
      run: sudo apt install -y libpcap-dev
    - name: Build
      run: cargo build --verbose --no-default-features --features pcap,stream
    - uses: actions/upload-artifact@v4
      with:
        name: reliquary-archiver-linux-pcap-x64
        path: target/debug/reliquary-archiver
